feat: resolver query challenges
ravnhq/DB-Nerdery-Challenges pull request #22
Opened 2023-05-01 15:31 UTC by irenehl

2023-05-09 13:58 UTC, FabioSotoDev commented
Good job ✅, both this challenge and the SQL bolt challenge LGTM 👍

2023-05-24 15:22 UTC, kevin-vm requested changes

2023-05-24 15:22 UTC, kevin-vm commented on README.md
> + SELECT em.uuid,
This query should take into consideration all employees, even those that don't belong to an office or don't have a boss (supervisor).

2023-06-26 22:26 UTC, kevin-vm approved these changes

2023-10-10 18:32 UTC, closed without merging